### ISSUE TITLE
Transient popup menus become persistent after displaying plot in MacOS

### ISSUE THREAD

**Issue by pptman** [andreabassi78/napari-sim-processor#2]
Transient user interface popups, eg for "interpolation" menu or the "input order" menus become persistent on the screen when running on macOS.  Does not happen on windows.   Probably a Qt or naperi issue?

**Comment by andreabassi78** [comment]
Does this issue show up when the plugin is not running? If yes we should move this issue somewhere else. If no please comment

**Comment by pptman** [comment]
Do you know of an alternative plugin that pops up a plot window to test the problem?  I agree that it is unlikely to be a napari-sim-processor issue.

**Comment by pptman** [comment]
Found the problem/fix.  Multiple phase plots would not appear at the same time on a Mac either so I set plt.show(block=False).  Now all plots appear and the transient pop-ups do not appear when they shouldn't.  Gui behaviour is unchanged in Windows.  The fix is in anglesandphases branch and can be merged to main along with the other changes there. I will close this issue.
