### ISSUE TITLE
HexSim analyser interface elements are centre justified on MacOS but left justified in Windows

### ISSUE THREAD

**Issue by pptman** [andreabassi78/napari-sim-processor#3]
Probably a Qt issue.  Would be worth fixing for a consistent look and feel.

![image](https://user-images.githubusercontent.com/17027217/167631170-2339d390-e9fe-4ed8-8e84-9f4056717357.png)

**Comment by andreabassi78** [comment]
We used a QFormLayout. Just found that for PySide2.QtWidgets.QFormLayout.formAlignment(),
 the default value depends on the widget or application style. For QMacStyle, the default is AlignHCenter | AlignTop ; for the other styles, the default is AlignLeft | AlignTop.
I forced it to ` AlignLeft`  on init. It's in the last commit. Haven't tried it on Mac yet. Please check if it's sufficient.
