### ISSUE TITLE
Plot calibration phase button

### ISSUE THREAD

**Issue by micropolimi** [andreabassi78/napari-sim-processor#4]
Plot calibration phases shows 3 curves per angle, while only one of the 3 curves is relevant to asses the phase.

**Comment by andreabassi78** [comment]
To clarify, are you using conventional 3x3 data?

**Comment by andreabassi78** [comment]
Fixed, now it's showing only one plot per angle. Please check so that we can close the issue. Thanks

**Comment by micropolimi** [comment]
It works! I try to close the issue
