### ISSUE TITLE
Adding access to CuPy methods from napari_sim_processor widget

### ISSUE THREAD

**Issue by pptman** [andreabassi78/napari-sim-processor#7]
@andreabassi78, I have created a branch (addcupy) where I have enabled access to all the CuPy methods from the main widget.  To do this I have changed the "use_torch" tickbox to a combobox with entries for numpy, torch and cupy (only adding torch and cupy to the list if they are available).  I have also added xcorr methods for cupy and torch and have added a section to README.md that briefly discusses GPU acceleration.

It all seems to run OK on my windows machine though I had to be a bit more aggressive in cleaning up GPU memory for CuPy processing as it seems that some settings to do with caching FFT plans are reset when running in new threads.  

It seems that torch calibration runs slower than cupy, which is not my earlier observation. I have investigated further by generating some timing data and displaying it in a QLineEdit widget:

  | Numpy | Torch | CuPy
-- | -- | -- | --
Calibration UsePhases Script | 1.250 | 0.190 | 0.329
Calibration UsePhases Napari | 1.290 | 1.532 | 0.318
  |   |   |  
Calibration Script | 0.534 | 0.138 | 0.174
Calibration Napari | 0.558 | 0.715 | 0.217
  |   |   |  
Batch reconstruct script | 2.802 | 0.432 | 0.685
Batch reconstruct Napari | 3.311 | 0.499 | 0.757

Any clues as to what has hit torch?

**Comment by pptman** [comment]
The tests were on 280x512x512 simulated hexsim data by the way with group 1 to select just one z-plane for calibration.

**Comment by pptman** [comment]
OK, found the issue (if instead of elif!!).  All is now well with the world!

  | Numpy | Torch | CuPy
-- | -- | -- | --
Calibration UsePhases Script | 1.250 | 0.190 | 0.329
Calibration UsePhases Napari | 1.290 | 0.199 | 0.318
  |   |   |  
Calibration Script | 0.534 | 0.138 | 0.174
Calibration Napari | 0.558 | 0.141 | 0.217
  |   |   |  
Batch reconstruct script | 2.802 | 0.432 | 0.685
Batch reconstruct Napari | 3.311 | 0.501 | 0.757

@andreabassi78 if you are happy with the changes then we can merge back into the main branch and close the issue.

**Comment by andreabassi78** [comment]
Excellent @pptman ! Yes please go ahead and merge this into the main branch. I will add a new tag and release a new version then, it is an important improvement.
