### ISSUE TITLE
AddCupy branch merged into main

### ISSUE THREAD

**Issue by pptman** [andreabassi78/napari-sim-processor#8]
@andreabassi78, I have merged the addcupy branch into main (see https://github.com/andreabassi78/napari-sim-processor/issues/7).  There is still the issue (https://github.com/andreabassi78/napari-sim-processor/pull/6) of whether torch (or cupy even) should be included in setup.cfg.  Both these need care when installing to get the correct version of cuda support.  Without specifying cuda version, torch in particular might install without any cuda support at all if installed automatically.  See https://pytorch.org/get-started/locally/

**Comment by andreabassi78** [comment]
Looks really great @pptman ! The message box is also cool and we should consider using it systematically.
I will release a new version, it looks like we had quite an improvement here.
Agree on the installation of cupy and torch. They are not straightforward. I changed the setup.cfg back to the first commit version, but I reopen issue #6 in case anyone else sees problems with cuda.  @micropolimi, @giorgiatortora and @andreabassi78 tested it without problems
