### ISSUE TITLE
error processing 3phase 1 angle 1 z stacks

### ISSUE THREAD

**Issue by GiorgiaTortora** [andreabassi78/napari-sim-processor#9]
I get this error when trying to recontract stacks with only 1 z-plane. No problems when z>1.

.., line 394, in get_current_p_stack
    assert z_index < s[2], 'Please choose a valid z step for the selected stack'
AssertionError: Please choose a valid z step for the selected stack

**Comment by andreabassi78** [comment]
Thanks @GiorgiaTortora, this is a problem that we had in the reshape function of the very first release (the one that you downloaded). It is now fixed. I close the issue
